apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whoami.fullname" . }}-{{ .Values.strategy.type }}
  labels:
    app: {{ include "whoami.name" . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ include "whoami.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "whoami.name" . }}
    spec:
      containers:
        - name: whoami
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
