{{- if (.Values.hpa.enabled) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "whoami.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "whoami.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
  name: {{ include "whoami.fullname" . }}-{{ .Values.strategy.type }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.autoscaling.behavior.scaleUp.selectPolicy }}
      policies:
        {{- range .Values.autoscaling.behavior.scaleUp.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      selectPolicy: {{ .Values.autoscaling.behavior.scaleDown.selectPolicy }}
      policies:
        {{- range .Values.autoscaling.behavior.scaleDown.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
{{- end }}
